spring:
    profiles:
        active: development
    output:
        ansi:
            enabled: ALWAYS
    mvc:
        favicon:
            enabled: false
server:
    port: 8000
app:
    token:
        expiration-time: 1800_000
    singpass:
        identity-provider:
            artifact-lifetime-clock-skew: 60_000
    service:
        services-folder-path: src/main/resources/services
        signature-lifetime-clock-skew: 25_000
management:
    endpoints:
        enabled-by-default: false

        web:
            exposure:
                include: health, prometheus
    endpoint:
        health:
            enabled: true
        prometheus:
            enabled: true
---

spring:
    profiles: development
app:
    token:
        signing-jwk: '{"kty":"RSA","alg":"RS512","use":"sig","n":"1Zhf5RMKNmAKm89kDZNK3ywNGqA2iujYJX9WqN7Vk-XJKzQTaXmLubTYjkPMRMUyY8I_1Zm1l8gxTjE3ArdrTF1Lx-JanGMS-zOFaFOH8ox_u6cWYR4RMFV_62KaI2IAnIcs6xqeffx2VO_X2X-geRQv-ut0GeDNNo2OKlGhkslfVUBEi4t-GrcCmjKh0wkr9j1pdOVxTYM_TCj1t8ALPr3IvaJhIlY-nd_9yszrQrzUbVGfNjFJanwIHQzoHkMajNTS_FQPJEaNdtb1mWIwokVXB0AY44QajCqcv5MWBJ_QV9yPv6cflMnCO3Fywa76AU4NZGOyCyLRH4ZQdeS-QQ","e":"AQAB","d":"FWwj6gi_1HZLehcR1N65-qojYlFBRytVSmV8HpHC4AOC6qddbw22uthtg88-9ILGrAS2fEjfUqrMbyg2eTpGM7GDwTdtmRPCupkPP0hpcSUwRnTapMDsPmnE26nXBcd1gj14ftf7n20rvRcVEgZf5OTmbwcgbNwEGP2XjZ0EVIFY-lDW8LdW_Q3IRcglhkrECGWoCEa13WbMWrn3j7VA8wak-tvIU50YUKuS0mKN3kss2lV5reKrdoRo84JMOPRJfbmoT3xkfxlCi4TEGLi5e-ZcRv6U9x5taYOEEUYDkt61jAAGlIf-VPf_5GSd16n7ZotOcp7DxIXkuz6Q4zHaNQ","p":"7Q5haG5yUXaKmDGSEU0_tSgDQ6tt27Y8FCRhSXmFmjxizLvOhX-iLehH8wTeRgoNOV8R7q1sSWwBP-BNKT1WvlruipA8MTckl2KrgD4IAMjn2TFVKiDCL99wait8YY-ItzymV8vO8f8cIMO910huyrJLDf7aLY2mvOZYTEUMFK8","q":"5qoJiTZdOgYYgDxx2tsR7qPJauvALStKXysd7f-ltyRpPSVvQAaqGPmtj4u6_dUOq4yonOQMVnMXrqbyxuRUrq9DyzONrtHrBUbd7fUVed0IRKW04CDWsZ6NqITRdnU8KNovxQlcIvQcwKYlUvFo4dJ4TpRD-06RBc65twG6-A8","dp":"wXHCu12lnCSH5LpO4B-RpVsJjucNtwV28Vjeqv6nr70nQrrfRMFqrtumGwIWAEGjmPWjxIlwnFmui1mWndiYOK4ripc5B1BgY8j4-qWkEj_gMrS3MrGYxUgoi_sAfPyMLDsp4utF7OSpJ3OUL2HER1RHOxyFHjdBoVS3KUYPHbE","dq":"GPfS7G1cDgnW4Rqp4FzSRhioltBKDxmehUqvhLGliHuCgMHqlu2hv-5W4TDo3s0PN3aUUddFlp4CtD8SDIFuwTHrjrVX4tKKNBoFr9pVpslMOdIOECy90KAvCUzHN6FdD7b-cL-gn4_5BMl3RNEo3zjfGPJnoW5RuGU2KR8g0_U","qi":"aeI55lLf9x33TawLOqtFs-RYIWRc2Pf-JZdJOMPlDUYJJ4khnFt4pYVCadpy0GRo0QoDm6Qv5M_XtOOzagWmzSDxeEEceL1VHBN1gYHvjNmoyiAhm7nKJC0-lZ1-_Vv5AK3nxGTnAuy_LN77VjyjrovOwzHr5pGXeWZhIF134BU"}'
    singpass:
        homepage-url: http://localhost:3000/
        service-provider:
            login-url: http://localhost:4000/login
        additional-info-request:
            static-json: '{"foo":"bar"}'
    corppass:
        homepage-url: http://localhost:3001/
        service-provider:
            login-url: http://localhost:4000/login
